# Generated by Django 4.1.4 on 2022-12-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrainement",
            name="section",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="section",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="section",
        ),
        migrations.AddField(
            model_name="entrainement",
            name="lieu",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="img",
            field=models.ImageField(
                default="profile-pictures/U9-mixte.png", upload_to="tounament-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="tournoi",
            name="lieu",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="profile-pictures/U9-mixte.png",
                        upload_to="tounament-pictures/",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basket.section",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entrainement",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basket.team",
            ),
        ),
        migrations.AddField(
            model_name="tournoi",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basket.team",
            ),
        ),
    ]
