# Generated by Django 4.1.4 on 2022-12-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_remove_entrainement_section_remove_photo_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournoi',
            name='resultat',
        ),
        migrations.AddField(
            model_name='resultat',
            name='tournoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.tournoi'),
        ),
        migrations.AddField(
            model_name='team',
            name='nom',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
