# Generated by Django 4.1.3 on 2022-12-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0003_remove_tournoi_resultat_resultat_tournoi_team_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="nom",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basket.team",
                    ),
                ),
            ],
        ),
    ]
