# Generated by Django 4.1.3 on 2022-12-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0004_alter_team_nom_player"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Player",
            new_name="Joueur",
        ),
    ]
