# Generated by Django 4.1.3 on 2022-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0005_rename_player_joueur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrainement",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="tournoi",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
