# Generated by Django 4.1.3 on 2022-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0006_alter_entrainement_date_alter_tournoi_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Team",
            new_name="Equipe",
        ),
        migrations.RenameField(
            model_name="entrainement",
            old_name="team",
            new_name="equipe",
        ),
        migrations.RenameField(
            model_name="joueur",
            old_name="team",
            new_name="equipe",
        ),
        migrations.RenameField(
            model_name="tournoi",
            old_name="team",
            new_name="equipe",
        ),
    ]
