# Generated by Django 4.1.3 on 2022-12-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0007_rename_team_equipe_rename_team_entrainement_equipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrainement",
            name="debut",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="tournoi",
            name="debut",
            field=models.TimeField(null=True),
        ),
    ]
