# Generated by Django 4.1.3 on 2022-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0008_alter_entrainement_debut_alter_tournoi_debut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrainement",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tournoi",
            name="date",
            field=models.DateField(default="2022-12-18"),
            preserve_default=False,
        ),
    ]
