# Generated by Django 4.1.3 on 2022-12-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0009_alter_entrainement_date_alter_tournoi_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrainement",
            name="categorie",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="categorie",
        ),
    ]
