# Generated by Django 4.1.3 on 2022-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0010_remove_entrainement_categorie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrainement",
            name="frequence",
            field=models.CharField(
                choices=[
                    ("HEB", "Hebdomadaire"),
                    ("MEN", "Mensuel"),
                    ("UNE", "Une fois"),
                ],
                default="UNE",
                max_length=5,
            ),
        ),
    ]
