# Generated by Django 4.1.3 on 2022-12-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0011_entrainement_frequence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrainement",
            old_name="equipe",
            new_name="equipe_1",
        ),
        migrations.RenameField(
            model_name="resultat",
            old_name="score_eux",
            new_name="score_1",
        ),
        migrations.RenameField(
            model_name="resultat",
            old_name="score_nous",
            new_name="score_2",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="advers",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="date",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="debut",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="equipe",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="fin",
        ),
        migrations.RemoveField(
            model_name="tournoi",
            name="lieu",
        ),
        migrations.AddField(
            model_name="tournoi",
            name="nom",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.TimeField(null=True)),
                ("fin", models.TimeField(blank=True, null=True)),
                ("lieu", models.CharField(max_length=100, null=True)),
                ("division", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("equipe_2", models.CharField(max_length=100)),
                ("forfait_1", models.BooleanField(default=False)),
                ("forfait_2", models.BooleanField(default=False)),
                (
                    "equipe_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basket.equipe",
                    ),
                ),
                (
                    "tournoi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="basket.tournoi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
