# Generated by Django 4.1.3 on 2022-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0012_rename_equipe_entrainement_equipe_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrainement",
            old_name="equipe_1",
            new_name="equipe",
        ),
        migrations.AddField(
            model_name="entrainement",
            name="salle",
            field=models.CharField(
                choices=[
                    ("SP", "Salle polyvalente"),
                    ("G", "Gymnase"),
                    ("H", "Halle des sports"),
                    ("LL", "Lycée Lafayette"),
                ],
                default="SP",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="entrainement",
            name="jour",
            field=models.CharField(
                choices=[
                    ("LU", "Lundi"),
                    ("MA", "Mardi"),
                    ("ME", "Mercredi"),
                    ("JE", "Jeudi"),
                    ("VE", "Vendredi"),
                    ("SA", "Samedi"),
                ],
                max_length=10,
            ),
        ),
    ]
