# Generated by Django 4.1.3 on 2022-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0013_rename_equipe_1_entrainement_equipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="forfait_1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="forfait_2",
        ),
        migrations.AddField(
            model_name="resultat",
            name="forfait_1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resultat",
            name="forfait_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="entrainement",
            name="debut",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="debut",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
