# Generated by Django 4.1.3 on 2022-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0015_remove_resultat_tournoi_resultat_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
