# Generated by Django 4.1.3 on 2022-12-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0016_alter_section_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrainement",
            name="lieu",
        ),
        migrations.RemoveField(
            model_name="match",
            name="lieu",
        ),
        migrations.AddField(
            model_name="tournoi",
            name="lieu",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
