# Generated by Django 4.1.3 on 2022-12-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0017_remove_entrainement_lieu_remove_match_lieu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="a_venir",
            field=models.BooleanField(default=True),
        ),
    ]
