# Generated by Django 4.1.3 on 2022-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0018_match_a_venir"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="photo",
            name="titre",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
