# Generated by Django 4.1.3 on 2022-12-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0019_album_alter_photo_titre"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basket.album",
            ),
        ),
    ]
