# Generated by Django 4.1.3 on 2022-12-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0020_photo_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="couverture",
            field=models.ImageField(
                default="tournament-pictures/logo.png", upload_to="tounament-pictures/"
            ),
        ),
    ]
