# Generated by Django 4.1.3 on 2022-12-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0021_album_couverture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="couverture",
            field=models.ImageField(
                default="tournament-pictures/logo.png", upload_to="albums-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="photo",
            field=models.ImageField(
                default="profile-pictures/U9-mixte.png",
                upload_to="tournament-pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="img",
            field=models.ImageField(
                default="profile-pictures/U9-mixte.png",
                upload_to="tournament-pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="img",
            field=models.ImageField(
                default="profile-pictures/U9-mixte.png",
                upload_to="tournament-pictures/",
            ),
        ),
    ]
