# Generated by Django 4.1.3 on 2022-12-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0022_alter_album_couverture_alter_equipe_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="album",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
