# Generated by Django 4.1.3 on 2023-01-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0023_remove_photo_album_delete_album_delete_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultat",
            name="match",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="basket.match",
            ),
        ),
    ]
