# Generated by Django 4.1.3 on 2023-01-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0024_alter_resultat_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="forfait_1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="forfait_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="score_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="score_2",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Resultat",
        ),
    ]
