# Generated by Django 4.1.3 on 2022-12-01 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=2000)),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/articles-pictures"
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
