# Generated by Django 4.1.4 on 2022-12-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Actu',
        ),
        migrations.RenameField(
            model_name='actu',
            old_name='title',
            new_name='titre',
        ),
    ]
