# Generated by Django 4.1.3 on 2022-12-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="function",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                default="profile-pictures/profile-base.png",
                upload_to="profile-pictures/",
            ),
        ),
    ]
