# Generated by Django 4.1.4 on 2022-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0002_alter_profile_function_alter_profile_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("FUNC", "Equipe Fonctionnelle"),
                            ("TECH", "Equipe Technique"),
                            ("COM", "Equipe de Communication"),
                        ],
                        max_length=5,
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "img",
                    models.ImageField(
                        default="profile-pictures/profile-base.png",
                        upload_to="profile-pictures/",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
