# Generated by Django 4.1.3 on 2022-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0003_profil_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "img",
                    models.ImageField(
                        default="profile-pictures/profile-base.png",
                        upload_to="partenaires-pictures/",
                    ),
                ),
            ],
        ),
    ]
