# Generated by Django 4.1.3 on 2022-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0004_partenaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profil",
            old_name="team",
            new_name="pole",
        ),
    ]
