# Generated by Django 4.1.3 on 2022-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0006_contactform"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="expediteur",
            field=models.EmailField(default="toto", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactform",
            name="message",
            field=models.CharField(default="bonjour toi", max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactform",
            name="titre",
            field=models.CharField(default="mail de contact", max_length=30),
            preserve_default=False,
        ),
    ]
