# Generated by Django 4.1.3 on 2022-12-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0007_contactform_expediteur_contactform_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="candidature",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactform",
            name="licence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREA", "Création"),
                    ("REN", "Renouvellement"),
                    ("MUT", "Mutation"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactform",
            name="nom",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="contactform",
            name="prenom",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="contactform",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("J", "Joueur"), ("E", "Entraineur"), ("B", "Bénévole")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactform",
            name="telephone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
