# Generated by Django 4.1.3 on 2023-01-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encadrement", "0009_licence_capacite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capacite",
            old_name="nom",
            new_name="capacite",
        ),
    ]
